apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-voting-app
  labels:
    app: azure-voting-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-voting-app
  template:
    metadata:
      labels:
        app: azure-voting-app
    spec:
      containers:
        - name: azure-voting-app
          image: rifielus.azurecr.io/azure-vote:ca7
          ports:
            - containerPort: 80
          env:
            - name: REDIS
              value: azure-vote-back