apiVersion: v1
kind: Service
metadata:
  name: azure-voting-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: azure-voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80